export interface XlsxColumn<T> {
  header: string;
  value: (row: T) => unknown;
}

export interface XlsxExportOptions {
  sheetName?: string;
  title?: string;
  subtitle?: string;
  includeGeneratedAt?: boolean;
  columnWidths?: number[];
  generatedBy?: string;
}

export interface PdfColumn<T> {
  header: string;
  value: (row: T) => unknown;
}

export interface PdfExportOptions {
  title?: string;
  subtitle?: string;
  orientation?: 'portrait' | 'landscape';
  generatedBy?: string;
  includeGeneratedAt?: boolean;
}

const INVALID_FILE_NAME_CHARS = /[<>:"/\\|?*]+/g;

const formatGeneratedAt = (): string =>
  new Date().toLocaleString('vi-VN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

const normalizeXlsxCellValue = (value: unknown): string | number | boolean => {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') {
    return value.replace(/\r?\n|\r/g, ' ').trim();
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return value;
  }

  return String(value)
    .replace(/\r?\n|\r/g, ' ')
    .trim();
};

const normalizePdfCellValue = (value: unknown): string => {
  const normalized = normalizeXlsxCellValue(value);

  if (typeof normalized === 'number') {
    return Number.isInteger(normalized)
      ? normalized.toLocaleString('en-US')
      : normalized.toLocaleString('en-US', {
          minimumFractionDigits: 0,
          maximumFractionDigits: 2,
        });
  }

  if (typeof normalized === 'boolean') {
    return normalized ? 'Yes' : 'No';
  }

  return normalized;
};

export const sanitizeFileName = (fileName: string): string => {
  const normalized = fileName.trim().replace(INVALID_FILE_NAME_CHARS, '-');
  return normalized.length > 0 ? normalized : 'download';
};

export const buildTimestampedFileName = (
  prefix: string,
  extension: string
): string => {
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  const hh = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');

  return sanitizeFileName(
    `${prefix}-${yyyy}${mm}${dd}-${hh}${min}${ss}.${extension}`
  );
};

export const getFileNameFromContentDisposition = (
  contentDisposition?: string | null
): string | null => {
  if (!contentDisposition) return null;

  const utf8Match = contentDisposition.match(/filename\*=UTF-8''([^;]+)/i);
  if (utf8Match?.[1]) {
    return sanitizeFileName(decodeURIComponent(utf8Match[1]));
  }

  const asciiMatch = contentDisposition.match(/filename="?([^";]+)"?/i);
  if (asciiMatch?.[1]) {
    return sanitizeFileName(asciiMatch[1]);
  }

  return null;
};

export const downloadBlobFile = (blob: Blob, fileName: string): void => {
  const anchor = document.createElement('a');
  const objectUrl = URL.createObjectURL(blob);

  anchor.href = objectUrl;
  anchor.download = sanitizeFileName(fileName);
  anchor.rel = 'noopener';

  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  URL.revokeObjectURL(objectUrl);
};

export const downloadTextFile = (
  content: string,
  fileName: string,
  mimeType = 'text/plain;charset=utf-8'
): void => {
  const blob = new Blob([content], { type: mimeType });
  downloadBlobFile(blob, fileName);
};

export const downloadXlsxFile = async <T>(
  rows: T[],
  columns: XlsxColumn<T>[],
  fileName: string,
  sheetNameOrOptions: string | XlsxExportOptions = 'Sheet1'
): Promise<void> => {
  const XLSX = await import('xlsx');

  const options: XlsxExportOptions =
    typeof sheetNameOrOptions === 'string'
      ? { sheetName: sheetNameOrOptions }
      : sheetNameOrOptions;
  const sheetName = options.sheetName ?? 'Sheet1';
  const includeGeneratedAt = options.includeGeneratedAt ?? true;
  const generatedAt = formatGeneratedAt();

  const metadataRows: Array<Array<string>> = [];
  if (options.title) {
    metadataRows.push([options.title]);
  }
  if (options.subtitle) {
    metadataRows.push([options.subtitle]);
  }
  if (includeGeneratedAt) {
    metadataRows.push([
      `Generated at: ${generatedAt}${
        options.generatedBy ? `  |  Generated by: ${options.generatedBy}` : ''
      }`,
    ]);
  }
  if (metadataRows.length > 0) {
    metadataRows.push(['']);
  }

  const headerRowIndex = metadataRows.length;
  const normalizedDataRows =
    rows.length > 0
      ? rows.map((row) =>
          columns.map((column) => normalizeXlsxCellValue(column.value(row)))
        )
      : [columns.map((_, index) => (index === 0 ? 'No data available' : ''))];

  const sheetRows = [
    ...metadataRows,
    columns.map((column) => column.header),
    ...normalizedDataRows,
  ];

  const worksheet = XLSX.utils.aoa_to_sheet(sheetRows);

  if (metadataRows.length > 0 && columns.length > 1) {
    worksheet['!merges'] = metadataRows.map((_, rowIndex) => ({
      s: { r: rowIndex, c: 0 },
      e: { r: rowIndex, c: columns.length - 1 },
    }));
  }

  const computedColumnWidths = columns.map((column, columnIndex) => {
    if (options.columnWidths?.[columnIndex]) {
      return { wch: options.columnWidths[columnIndex] };
    }

    const values = normalizedDataRows.map((row) =>
      String(row[columnIndex] ?? '')
    );
    const maxLength = Math.max(
      column.header.length,
      ...values.map((value) => value.length)
    );

    return { wch: Math.min(Math.max(maxLength + 4, 14), 60) };
  });

  worksheet['!cols'] = computedColumnWidths;
  worksheet['!rows'] = sheetRows.map((_, rowIndex) => {
    if (rowIndex < headerRowIndex) {
      return { hpt: 18 };
    }

    if (rowIndex === headerRowIndex) {
      return { hpt: 22 };
    }

    return { hpt: 18 };
  });

  const lastColumnLetter = XLSX.utils.encode_col(columns.length - 1);
  const headerExcelRow = headerRowIndex + 1;
  worksheet['!autofilter'] = {
    ref: `A${headerExcelRow}:${lastColumnLetter}${headerExcelRow}`,
  };

  const headerStyle = {
    font: { bold: true, color: { rgb: 'FFFFFF' } },
    fill: { fgColor: { rgb: '0F766E' } },
    alignment: { horizontal: 'center', vertical: 'center', wrapText: true },
  };

  columns.forEach((_, columnIndex) => {
    const address = XLSX.utils.encode_cell({
      r: headerRowIndex,
      c: columnIndex,
    });
    const cell = worksheet[address] as { s?: unknown } | undefined;
    if (cell) {
      cell.s = headerStyle;
    }
  });

  for (let rowIndex = 0; rowIndex < metadataRows.length; rowIndex += 1) {
    const address = XLSX.utils.encode_cell({ r: rowIndex, c: 0 });
    const cell = worksheet[address] as { s?: unknown } | undefined;
    if (cell) {
      cell.s = {
        font: {
          bold: rowIndex === 0,
          color: { rgb: rowIndex === 0 ? '0F172A' : '334155' },
          sz: rowIndex === 0 ? 13 : 10,
        },
        alignment: { horizontal: 'left', vertical: 'center', wrapText: true },
      };
    }
  }

  normalizedDataRows.forEach((row, dataIndex) => {
    row.forEach((value, columnIndex) => {
      const address = XLSX.utils.encode_cell({
        r: headerRowIndex + 1 + dataIndex,
        c: columnIndex,
      });
      const cell = worksheet[address] as { z?: string } | undefined;
      if (!cell || typeof value !== 'number') return;

      cell.z = Number.isInteger(value) ? '#,##0' : '#,##0.00';
    });
  });

  const workbook = XLSX.utils.book_new();
  workbook.Props = {
    Title: options.title ?? sheetName,
    Subject: options.subtitle,
    Author: options.generatedBy ?? 'AuraEyes',
    CreatedDate: new Date(),
  };
  XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);

  const workbookBytes = XLSX.write(workbook, {
    bookType: 'xlsx',
    type: 'array',
  });

  const blob = new Blob([workbookBytes], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });

  downloadBlobFile(blob, fileName);
};

export const downloadPdfTableFile = async <T>(
  rows: T[],
  columns: PdfColumn<T>[],
  fileName: string,
  options?: PdfExportOptions
): Promise<void> => {
  const [{ default: JsPdf }, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  const autoTable = (
    autoTableModule as { default: (...args: unknown[]) => void }
  ).default;
  const doc = new JsPdf({
    orientation: options?.orientation ?? 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedAt = formatGeneratedAt();
  const title = options?.title ?? 'Export Report';
  const subtitle = options?.subtitle;
  const includeGeneratedAt = options?.includeGeneratedAt ?? true;

  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, pageWidth, 54, 'F');
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text(title, 30, 24);
  doc.setFontSize(8.5);
  doc.setTextColor(226, 232, 240);
  doc.text(`AuraEyes Export | Rows: ${rows.length}`, 30, 40);

  let currentY = 72;
  if (subtitle) {
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(subtitle, 30, currentY);
    currentY += 14;
  }

  if (includeGeneratedAt) {
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(
      `Generated at: ${generatedAt}${
        options?.generatedBy ? ` | Generated by: ${options.generatedBy}` : ''
      }`,
      30,
      currentY
    );
    currentY += 14;
  }

  const tableRows =
    rows.length > 0
      ? rows.map((row) =>
          columns.map((column) => normalizePdfCellValue(column.value(row)))
        )
      : [columns.map((_, index) => (index === 0 ? 'No data available' : ''))];

  const tableWidth = pageWidth - 60;
  const weightTotal = columns.reduce(
    (total, column) => total + Math.max(column.header.length, 12),
    0
  );
  const columnStyles = columns.reduce(
    (styles, column, index) => {
      const ratio = Math.max(column.header.length, 12) / weightTotal;
      styles[index] = {
        cellWidth: Math.max(70, Math.min(280, Math.floor(tableWidth * ratio))),
      };
      return styles;
    },
    {} as Record<number, { cellWidth: number }>
  );

  autoTable(doc, {
    startY: currentY,
    head: [columns.map((column) => column.header)],
    body: tableRows,
    theme: 'grid',
    styles: {
      fontSize: 8.5,
      cellPadding: 5.5,
      valign: 'middle',
      textColor: [15, 23, 42],
      lineColor: [203, 213, 225],
      lineWidth: 0.35,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [15, 118, 110],
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
      lineColor: [15, 118, 110],
      lineWidth: 0.6,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles,
    margin: { top: 24, right: 30, bottom: 28, left: 30 },
    didDrawPage: (data: { pageNumber: number }) => {
      const { pageNumber } = data;
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Page ${pageNumber}`, pageWidth - 54, pageHeight - 12, {
        align: 'right',
      });
    },
  });

  doc.save(sanitizeFileName(fileName));
};
