export { default as OphthalmologistDashboard } from './dashboard';
export { default as OphthalmologistProfilePage } from './profile';
export { default as PatientsPage } from './patients';
export { default as ScreeningsPage } from './screenings';
export { default as AppointmentsPage } from './appointments';
export { default as SettingsPage } from './settings';
export { default as SchedulesPage } from './schedules';
export { default as SlotManagementPage } from './slot-management';
export { default as LeaveRequestsPage } from './leave-requests';
